I2PC/scipion

pyworkflow/em/packages/eman2/protocol_refineasy.py, pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py, pyworkflow/em/packages/relion/protocol_classify3d.py, pyworkflow/em/packages/relion/protocol_refine3d.py, pyworkflow/em/packages/xmipp3/protocol_projmatch/protocol_projmatch.py, pyworkflow/tests/em/protocols/test_protocols_xmipp_2d.py, scripts/run_tests.py
Three fixes:
* added missing parameter **errors** to the *_validateDim* function
* initialized counter when running tests
* removed the use of os.system('scipion....') in break symmetry test
=> Three more fixes

pyworkflow/tests/em/data/test_metadata.py, software/em/xmipp/libraries/bindings/python/python_metadata.cpp, software/em/xmipp/libraries/data/metadata_sql.cpp
In the devel branch a bug was introduced in the MetaData.removeDuplicates function when used with no label. It was affecting the projection matching protocol to give weird results and failing at some steps.
@cossorzano, @rmarabini , @juannavascalvente  We should always add tests to reflect the current problems and test the function in order to check that it does not break previous funcionality.
A new test was added for removeDuplicate (in Python) and the label parameter is now ported to python binding.
=> Fixed bug in MetaData.removeDuplicates function

pyworkflow/em/packages/grigoriefflab/viewer.py, pyworkflow/em/packages/xmipp3/viewer.py, pyworkflow/em/viewer.py, software/em/xmipp/java/src/xmipp/viewer/ctf/CTFAnalyzerJFrame.java, software/em/xmipp/java/src/xmipp/viewer/models/GalleryData.java, software/em/xmipp/java/src/xmipp/viewer/particlepicker/extract/ExtractPickerJFrame.java, software/em/xmipp/java/src/xmipp/viewer/particlepicker/training/gui/SupervisedPickerJFrame.java
Main fixes:
- SetOfCtf visualization is the same if you double click the object or in the Analyze Results.
- CtfView is now centralized and the labels are passed if they are present in the data (xmipp labels only appears when xmipp results)
- The display CTF fitting work as well for import ctf from ctffind4
- The PSD profile now works with ctf:mrc trick.
@azazellochg , could you check if these changes work for you? I tested import but from scipion-ctffind4, could you test for original-ctffind4 and for relion-ctffind4?
=> Ctf viewer clean-up and PSD display fixed

CHANGELOG.md, pyworkflow/em/convert.py, pyworkflow/em/packages/grigoriefflab/protocol_ctffind.py, pyworkflow/em/packages/relion/protocol_base.py, pyworkflow/em/packages/spider/convert.py, pyworkflow/em/packages/spider/protocol/protocol_classify_diday.py, pyworkflow/em/packages/spider/protocol/protocol_classify_ward.py, pyworkflow/em/packages/xmipp3/__init__.py, pyworkflow/em/packages/xmipp3/protocol_break_symmetry.py, pyworkflow/em/packages/xmipp3/protocol_extract_particles.py, pyworkflow/em/packages/xmipp3/protocol_extract_particles_movies.py, pyworkflow/em/packages/xmipp3/protocol_multireference_alignability.py, pyworkflow/em/packages/xmipp3/protocol_projmatch/projmatch_form.py, pyworkflow/em/packages/xmipp3/protocol_write_testP.py, pyworkflow/em/packages/xmipp3/viewer.py, pyworkflow/em/protocol/protocol_ctf_assign.py, pyworkflow/em/protocol/protocol_sets.py, pyworkflow/gui/form.py, pyworkflow/object.py, pyworkflow/tests/em/data/test_data.py, pyworkflow/tests/em/protocols/test_protocols_grigoriefflab.py, scipion
Summary:
- Computed phaseShifts in CTFFIND4, updated references
- Centralized viewer of SetOfCTF for both xmipp and ctffind, and the same from Analyze Results or double click on results.
- Fixed problem with ctf:mrc extension of PSD and bigger than 256 pixels
- Validations on relion viewers and on extract particles
- Used shorter name to run Spider script
=> RELEASE V1.0.0  2016-02-20

software/em/xmipp/java/src/xmipp/utils/XmippWindowUtil.java, software/em/xmipp/java/src/xmipp/viewer/windows/ExportImagesJDialog.java
Show error info if something happens when exporting particles in ShowJ.
=> hide content parameter in blockGUI method when activating the infiniteProgress

.gitignore, pyworkflow/gui/dialog.py, pyworkflow/gui/project/viewdata.py, pyworkflow/gui/text.py
Objects comments were added new lines on each update. Now final new lines are trimmed in any text in a Text box.
Allow ascii characters in data vie summary.
This closes #353
=> Stop adding new lines in textboxes + ascii error in data view.

software/em/xmipp/libraries/data/metadata_sql.cpp
The static variable "int MDSql::rc;" is shared by different functions in the metadata_sql.cpp file. This could produce race conditions when several threads execute SQL sentences and overwritting this return variable.
Some of the functions do not really need to use this variable. The new version does not store the return value if not needed and keeps this variable when using a static member function.
=> Fixing race conditions when storing return value from sql functions

software/em/xmipp/libraries/data/image_operate.cpp
This is related with #466  issue. Now, there is a bug when the object is a metadata with one element. We need to fix it.
=> the conditional was restored as it is in v1.0 branch. 

pyworkflow/gui/project/viewprotocols.py, pyworkflow/gui/text.py, pyworkflow/project.py, pyworkflow/protocol/protocol.py, pyworkflow/utils/process.py, software/em/xmipp/java/src/xmipp/viewer/models/MetadataTableModel.java
Now it's checking properly the PID.
Also check only against running status, leaving outside the rest active ones(launched, interactive).
Additionally: Do not try to remove a protocol if delete is pressed while on the search box (the one in the logs tab).
Closes #183 
Closes #511 
Use \u format for unicode special characters, since the characters it self  generates compiling error in javac when the locales are not set properly.
=> Check pid for protocol status

pyworkflow/em/packages/eman2/protocol_initialmodel.py, pyworkflow/em/packages/eman2/viewer.py, pyworkflow/em/packages/gctf/viewer.py, pyworkflow/em/packages/grigoriefflab/viewer.py, pyworkflow/em/packages/xmipp3/nma/viewer_nma.py, pyworkflow/em/packages/xmipp3/protocol_movie_opticalflow.py, pyworkflow/em/packages/xmipp3/viewer.py, pyworkflow/em/protocol/protocol_movies.py, pyworkflow/em/showj.py, pyworkflow/em/viewer.py, pyworkflow/gui/project/project.py
Object-Commands are commands passed to Showj Java app when visualizing some to dynamically add command available for specific items. Then Showj call back the project gui that is listening at some port and react to this commands. 
Before, the gui/project.py contains the dirty includes for the commands. Now it has a **registerCommand** method to register new command without changing the code at this levels.
After this, I added 3 extra commands to improve Eman2 initial-volume visualization as suggested by @azazellochg  in #546 
@azazellochg , could you double check that everything is working as expected?
=> Re-factored how Object-Commands are handled

pyworkflow/tests/em/data/test_data.py, pyworkflow/tests/em/data/test_metadata.py, pyworkflow/tests/em/programs/base.py, pyworkflow/tests/em/programs/test_pythoninferface_xmipp.py, pyworkflow/tests/em/workflows/test_workflow_existing.py, pyworkflow/tests/model/test_canvas.py, pyworkflow/tests/model/test_mappers.py, pyworkflow/tests/model/test_object.py, pyworkflow/tests/tests.py, scripts/run_tests.py, software/em/xmipp/applications/tests/test_emx/batch_test_emx.py, software/em/xmipp/applications/tests/test_pysqlite/batch_test_pysqlite.py
The scipion script has been modified to accept a new parameter "--label" that filters the test to be listed by "--show" or executed by "--run". This new label parameter accepts a list of labels and filters the test that match the set of labels.
Currently the test accept three label values: pull, daily and weekly. It defines the execution of the test in buildbot: pull when it must be executed under a new pull request, daily to be executed once a day and weekly to be executed during the weekend. 
At this moment, only one TestCanvas is defined as pull request, and all the others are set to weekly.
=> Adding labels to scipion script to filter tests

software/em/xmipp/applications/tests/test_metadata/test_metadata_main.cpp, software/em/xmipp/libraries/data/metadata.cpp, software/em/xmipp/libraries/data/metadata.h, software/em/xmipp/libraries/data/metadata_sql.cpp, software/em/xmipp/libraries/data/metadata_sql.h, software/em/xmipp/libraries/data/xmipp_funcs.cpp, software/em/xmipp/libraries/data/xmipp_funcs.h
There are a couple of functions, "getTime" and "timeval_subtract", in the "test_metadata_main.cpp" file that could be moved to another file as they are used to measure time executions. 
The addRow2, setRow2 and getRow2 are the new implemented functions and have been removed to use the old ones as they are the reference functions. Those three functions have been also added to some test to check that their behavior is the same as the reference functions.
=> Updating metadata interface and including tests

pyworkflow/em/protocol/protocol_sets.py, pyworkflow/object.py, pyworkflow/tests/em/protocols/test_protocols_sets.py, pyworkflow/tests/model/test_object.py
Allow to do the join-set on sets which items could have different attributes. Only the common attributes are preserved in the output set.
=> Join different attrs

pyworkflow/em/packages/xmipp3/__init__.py, pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_add_noise.py
add_noise protocol has been moved from
pyworkflow/em/packages/xmipp3/
to
pyworkflow/em/packages/xmipp3/protocol_preprocess
This broke two imports
import from add_noise in init.py
import of convert in protocol_add_noise.py
The "moved" protocol did not arise any error because the system was able to find the compiled pyc in the old location. Of course new instalation failed because no binary file has present in the old location.
Test scipion test tests.em.protocols.test_protocols_add_noise.TestAddNoise was successful
=> Rm fix addnoise

software/em/xmipp/java/src/xmipp/viewer/windows/EditLabelsJDialog.java
This is not strictly a bug-fix, but was an easy to implement feature requested a long time ago (and many more times) by Jaime Martin Benito. He manipulates metadatas from showj GUI and it finds helpful the ability to delete many columns at once. The change has little impact on the rest of the codebase.
=> Remove multiple metadata labels from showj

pyworkflow/apps/pw_config.py
modify pw_config.py so it can handle python3.
The problem is the function raw_input (python2) vs input (python3) used to read the keyboard.
Note in order to check this it is not enough to launch the installation as
python3 ./scipion config
or
python2 ./scipion config
You need to create a virtual environment for python2 and python3 and switch between them. 
This is a bit scary because it does mean that if we run the script as
python3 ./scipion install
at some point the system python is called as "python" using the default path. That is, if two installation of python are set in the same machine we may start  the configuration using one python and change to another in the middle.
(yes, I know the explanation is not crystal clear)
=> update config script so it can handle python3

config/templates/scipion.template
Fix for error 'memcpy' was not declared in this scope when compiling with cuda enabled.
---
Apparently, /usr/include/string.h changed from glib2.22 to glibc2.23 (https://fossies.org/diffs/glibc/2.22_vs_2.23/string/string.h-diff.html). The added code comes at the bottom of the file and is:
#if defined __USE_GNU && defined __OPTIMIZE__ \
&& defined __extern_always_inline && __GNUC_PREREQ (3,2)
#undef mempcpy
#undef __mempcpy
#define mempcpy(dest, src, n) __mempcpy_inline (dest, src, n)
#define __mempcpy(dest, src, n) __mempcpy_inline (dest, src, n)
__extern_always_inline void *
__mempcpy_inline (void *__restrict __dest,
const void *__restrict __src, size_t __n)
{
return (char *) memcpy (__dest, __src, __n) + __n;
}
#endif
The ways I've seen to stop this new code from triggering the memcpy …
=> fix for error 'memcpy' was not declared in this scope

pyworkflow/em/data.py, pyworkflow/em/protocol/protocol_align_movies.py
Processing of input movies in compressed format was broken (presumably with streaming changes)
The problem was that the decompressed movie name was used for some outputs and in other context the original name was used to create the output object. 
Now with this fix, the root (without the last two extensions) will be used for the output and for the set creation. 
This should fix issue #1081. So after this PR is tested and merged, the issue can be closed.
Moreover, a minor code formatting was done in data.py and removed some debug print.
=> Release 1.1.1 bug compressed movies

pyworkflow/em/packages/xmipp3/protocol_ctf_micrographs.py, pyworkflow/tests/em/protocols/test_protocols_ctf_streaming.py
Added the xmipp ctf estimation protocol in streaming (protocol_ctf_micrographs). This time coming from the branch release-1.1.facilities-devel. 
The code has been modified following the recommendations of @josuegbl
A simple test to chek the performance of the new protocol is also included in test_protocols_ctf_streaming.
=> New xmipp ctf estimation in streaming from branch release-1.1.facilities-devel

pyworkflow/em/packages/gctf/convert.py
@azazellochg I has fixed a bug in parsing Gctf log files.
When the 'High resolution refinement' and not the 'Phase shift estimation' the line produced was as below:
23846.26    23525.42       61.84    0.521613  Final Values (Hres refine)
Adding the extra '(Hres refine)' string and making the number of elements after split greater...and broken the current parsing. 
I have changed the parsing a little bit and this error is fixed. Can you double check my changes to make sure it is working as expected? (I have passed the Gctf tests already)
=> Fix parse gctf

software/em/xmipp/libraries/data/metadata_label.h, software/em/xmipp/libraries/reconstruction/classify_extract_features.cpp, software/em/xmipp/libraries/reconstruction/classify_extract_features.h, software/em/xmipp/libraries/reconstruction/evaluate_coordinates.cpp
Added variance features to xmipp_classify_extract_features
- feature vector consists of 17 values: 16 variance feature values (for 4x4 regions of a single particle) + 1 feature value as their combination that is used for eliminating false positives or the bad particles
=> Added variance features

software/em/xmipp/libraries/reconstruction/reconstruct_fourier_accel.cpp
Due to inconsistency in header files, it was not possible to compile code with GCC 7.
=> fixing #1254 (reconstruct_fourier_accel does not compile with gcc7)

install/script.py, pyworkflow/em/convert.py, pyworkflow/em/packages/motioncorr/convert.py, pyworkflow/em/packages/motioncorr/protocol_motioncorr.py, pyworkflow/em/protocol/protocol_movies.py, pyworkflow/tests/em/protocols/test_protocols_motioncorr.py
Changes in this PR:
* Updated version of motioncor2-1.0.1
* Removed conversion from tif for motioncor2
Slightly more general way to express that input movies need to be converted to a given format.
=> Release 1.1.facilities mc2

software/em/xmipp/libraries/reconstruction/reconstruct_fourier_accel.cpp, software/em/xmipp/libraries/reconstruction/reconstruct_fourier_accel.h
This fix aim e.g.  gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18) and on CentOS 6.9, where current code cannot be build (error: ISO C++ forbids initialization of member 'buffer1').
=> fixing build with old compilers

pyworkflow/em/packages/xmipp3/convert.py, pyworkflow/em/packages/xmipp3/protocol_eliminate_empty_particles.py, software/em/xmipp/libraries/reconstruction/image_eliminate_empty_particles.cpp, software/em/xmipp/libraries/reconstruction/image_eliminate_empty_particles.h
- changing condition in convert.py, which was not used before
- denoising is by default turned off (it is too slow with denoising for large sets of particles)
- optional denoising could be now balanced by parameter
- performance was enhanced by removing cloning particles
- c++ program stores all the good and bad particles in files, in streaming also increment/temp files are used to make process faster but later, these temp files are removed
- doneList in no longer used
- it was tested with streaming, without streaming, and without streaming on very large dataset, also TestXmippEliminatingEmptyParticles is ok
=> Fixing problems with elimination of empty parts

pyworkflow/em/packages/xmipp3/protocol_eliminate_empty_particles.py, pyworkflow/em/packages/xmipp3/protocol_trigger_data.py
Removing unused functions from protocol_trigger_data.py
Added small fix when particle IDs are not sequential (also for eliminate empty particles)
=> Trigger data - remove unused functions

pyworkflow/em/packages/motioncorr/protocol_motioncorr.py
A space before -gpu argument is need it to separate from the previous argument.
=> Bug fixing in -gpu argument

pyworkflow/em/packages/resmap/protocol_resmap.py
Part of fixes for #1610
This one looks safe based on the lack of retained references from the `Plotter` creation functions.  tests.em.protocols.test_protocols_resmap passes and analyzing the results in the gui it looked like everything was there.
=> Closes figures after saving in protocol_resmap

pyworkflow/tests/em/programs/test_programs_xmipp.py
The threshold for the assertion in the phantomSimulateMicroscope test has been increased in order to pass in different branches where the approach has been slightly changed.
=> Add a threshold in phantom_simulate_microscope Test

pyworkflow/em/packages/relion/protocol_autopick_v2.py, pyworkflow/em/packages/relion/protocol_base.py, pyworkflow/em/packages/relion/wizard.py, pyworkflow/em/packages/xmipp3/convert.py, pyworkflow/em/packages/xmipp3/protocol_extract_particles_movies.py, pyworkflow/gui/form.py, pyworkflow/project.py
* Fixed bug when using Relion picking: the run of the protocol for optimize the picking params was generating a set of micrographs (subset based on defocus) and a set of coordinates (linked to the subset), but when executing for the whole set, still the output coordinates was there and with bad reference to microgasph!!! Solution: change the name to 'outputXXXSubset'. Still, it seems to be a deeper problem with deleting outputs of a protocol in a Continue mode.
* Alleviated the problem of selecting input CTF and getting no input in the select dialog...now a refresh param is passed as True and it seems to be less problematic now, not sure if will pick up the inputs immediately. The downside is that it takes a bit more of time when opening, but I think is a good price to pay for avoiding …
=> Release 1.2.1 relion fixes

pyworkflow/em/convert.py, pyworkflow/em/protocol/monitors/report_html.py
Use flip flags in the HTML report for the mic and PSD
Fix bug in HTML report generation where no ctf protcol is added and alignment hasn't computed the PSD.
Closes #1612
=> convertThumbnail: has optional flip flags (x, and y)

pyworkflow/em/packages/relion/viewer.py, pyworkflow/em/packages/xmipp3/protocol_particle_pick.py, pyworkflow/em/packages/xmipp3/viewer.py, pyworkflow/em/protocol/protocol_align_movies.py, pyworkflow/em/showj.py
There is a very important bug introduced in #1693 that stop visuazliations to show up mainly for coordinates and some other cases. 
@pconesa and @rmarabini , I think you should have been more careful with the changes introduced in the Java memory param, it was changed from integer to string, but all the cases were not tested. It was not even basically tested that most common showj use cases were working!!! I think we should avoid this issues, specially for a release that is about to be out. You "fixed" the case for visualizing movies, that is not commonly used...and you broke the Xmipp picker, coordinates visualization and other cases.
I will take also my part of responsibility, since I reviewed this PR and this issue passed. The other problem, is this original PR was about DM4 support, …
=> CRITICAL visualization BUG in release-1.2.1

pyworkflow/em/protocol/protocol_import/__init__.py, pyworkflow/em/protocol/protocol_import/coordinates.py, pyworkflow/em/protocol/protocol_import/ctfs.py, pyworkflow/em/protocol/protocol_import/particles.py, pyworkflow/em/wizard.py, pyworkflow/tests/em/protocols/test_protocols_import_coords.py, pyworkflow/tests/em/protocols/test_protocols_import_ctfs.py
These changes come from [EMAN2.21 PR](https://github.com/I2PC/scipion/pull/1616):
- new ProtImportCoordinatesPairs and a test
- imports from EMAN2: ctfs (json) + test, sets/particles (lst)
This closes #1500
=> add new eman-related imports; add coord pairs import

pyworkflow/em/protocol/protocol_movies.py
When the gainImage was the empty string, the protocol was wrongly raising an Exception.
=> Fixed bug when gainImage is empty string

install/script.py
ShowJ uses png library, who depends on zlib. Then, if png isn't installed in Scipion, ShowJ find png in the system that can be incompatible with the zlib installed in Scipion by default and puted first in the LD_LIBRARY_PATH.
=> Set png library as default=True

pyworkflow/em/packages/xmipp3/viewer.py, pyworkflow/em/showj.py
DataView.setMemory( ) and showj.getJvmMaxMemory() works with strings, however we want to increase the available memory to show movies in 1Gb.
I don't know if there is a cleaner way bu this fix the bug.
=> Bug fixing in xmipp's viewer.py: 'str' + 'int'

install/script.py, pyworkflow/tests/tests.py, pyworkflow/utils/mpi.py
previous mpi python version didn't work for modern openMPI versions like 3.0. This has fixed my errors.
I've trested mpi with scipion test xmipp3.tests.test_protocols_xmipp_mics.TestXmippExtractParticles
But none of the protocols inside used mpi. So I manually run one with mpi.
use source, instead of dest for irecv
fix bug in test.py --> useQueue()
=> install mpi4py 3.0.3

config/templates/protocols.template, pyworkflow/em/protocol/protocol.py, pyworkflow/em/protocol/protocol_particles.py, pyworkflow/mapper/sqlite.py, pyworkflow/object.py, pyworkflow/tests/em/data/test_data.py
The **aim** of this commit is to **speed up searchs in metadatas.** Jaime Martin Benito reported that extracting particles form a large dataset (6000 micrographs and 150 coordinates per micrograph) spent several hours converting the coordinate fle (in sqlite) to xmipp (pos) coordinate files.
The more consuming code was the loop
```
for micKey, mic in micDict.iteritems():
if counter % 50 == 0:
b = datetime.now()
print b-a, 'reading coordinates for mic number', "%06d" % counter
sys.stdout.flush()  # force buffer to print
counter += 1
micId = mic.getObjId()
coordList = []
self.debug("Loading coords for mic: %s (%s)" % (micId, micKey))
for coord in coordSet.iterItems(where='_micId=%s' % micId):
```
In order to reduce the serching time we explore the posibility od adding pragma to the database …
=> Add indexes and pragma instruction for database

install/script.py
Seems to fix some python installation in Ubuntu 18
Update tif lib to use BigTiff files.
Tested and Show J was able to open bigtiff sample files.
https://www.awaresystems.be/imaging/tiff/bigtiff.html#samples
=> Update Python to 2.7.15

pyworkflow/em/convert/atom_struct.py, pyworkflow/em/protocol/protocol_import/sequence.py, pyworkflow/em/wizard.py, pyworkflow/tests/em/data/test_convert_atom_struct.py
Added method "extractChain" to atom_struct.py that is able to extract a chain from an atomic struct. A corresponding wizard has been implemented
TEST: ./scipion test pyworkflow.tests.em.data.test_convert_atom_struct.TestAtomicStructHandler.testFunctionSelectChain
The wizard is used by "import_sequence" protocol and scipion-em-atom_struct_utils which is a new plug-in
=> Add new method to atomic_struct.py that can extract a particular chain from an atomic model

pyworkflow/em/protocol/protocol_batch.py, pyworkflow/em/protocol/protocol_particles_picking.py, pyworkflow/gui/form.py, pyworkflow/gui/project/viewprotocols.py, pyworkflow/project/project.py, pyworkflow/protocol/protocol.py, pyworkflow/tests/em/protocols/test_protocols_sets.py, pyworkflow/tests/test_protocol_output.py
Populate the outputList and store it.
iterOutputAttributes allows None as class to return all.
use iterOutputAttributes without EMObject and replace iterOutputsEM by
iterOutputAttributes
@delarosatrevin this is how I understood we should do this after our conversation.
I've unified calls to outputs iteration to a single one (iterOutputAttributes), but left iterOutputEM. Scipion is not using it, except in a test, but I guess plugins might be using them.
=> Refactorization of outputs using _outputs List

pyworkflow/tests/em/workflows/test_workflow_streaming.py
Due to bug in eman/sparx 2.21, sparx picking step was replaced with relion picking.
https://github.com/scipion-em/scipion-em-relion/issues/14
=> fix failing streaming test

pyworkflow/em/convert/image_handler.py, pyworkflow/tests/em/data/test_data.py, scipion
Two main small changes here:
* Allow variables (e.g $USER) in the scipion.conf files: this is very useful when the projects should not be located by default in home and with this change, we can set this automatically without user need to create links or move data.
* Fixed bug in ImageHandler.truncateMask when volumes came from Relion (.mrc without 2014 MRC flags). Additional, a new dimension can be passed to the new mask, this is needed for a protocol in relion to adjust the mask size at the same time as truncating it. A test was added for this case.
=> Jmrt minor changes

pyworkflow/templates/protocols.template
Xmipp (localSharpening) and LocScale already have this section and it make sense to be in the tree after refine instead of at the end if not defined here.
Also I propose to include RelionPostProcess protocol in https://github.com/scipion-em/scipion-em-relion/pull/52 PR.
It will looks like:
=> Including postprocess in 3D section of protocol.conf

pyworkflow/em/protocol/protocol_align_movies.py
partly addressing https://github.com/I2PC/xmipp/issues/132
deprecating:
computePSD()
composePSD()
computePSDs()
and adding new alternatives, which do not require repeated data store/load
=> Using binding to PSD estimation

pyworkflow/em/protocol/monitors/protocol_monitor.py
When a user sets a mail to warn if some acquisition value goes out of range and the mail sending fails, the monitor is freezed due to the error, so far.
With this update, we just print the error and the warning while the monitor continues working. This make sense to be able to keep populating the HTML report.
=> Catching the error when a warning mail sending fails

pyworkflow/tests/test_utils.py, pyworkflow/utils/progressbar.py
Dear @rmarabini , as my review of PR #1998 ...I'm proposing some re-factoring to your ProgressBar class. I didn't want to directly commit my changes into your branch, so I have created this other PR to discuss my proposal. 
Regarding the refactoring...I had two main concerns:
* There was a lot of boiler plate code for flush, print, increment, etc...which relates somehow to the second point here
* There was no clear API, so the access was done directly to the attributes both for getting or setting then. I have introduced a  minimal set of functions...if you need access to other properties, you can add getX/setX methods...although my personal recommendation is to keep it simple and minimal.
Regarding the mystery of stdout redirection...the issue was in your code. There is a STRONG …
=> Refactoring proposal for ProgressBar class, fixed stdout mystery

pyworkflow/tests/test_utils.py, pyworkflow/utils/__init__.py, pyworkflow/utils/progressbar.py
Prints a progressbar. There are four predefined formats: dot, deafult, full, objedid
Esamples
```
dot
.............................................
full
[======                                  ] 1/3 (  33%) 2 to go
default
Progress: [                                        ]   0%
objectid
[                                        ] 0/3 (  0%) (objectId=33)          
```
Tests; 
./scipion test pyworkflow.tests.test_utils.TessProgressBar.test_dot
./scipion test pyworkflow.tests.test_utils.TessProgressBar.test_default
./scipion test pyworkflow.tests.test_utils.TessProgressBar.test_full
./scipion test pyworkflow.tests.test_utils.TessProgressBar.test_objectid
Example of use:
```
from time import sleep
from pyworkflow.utils import Progressbar
progress = ProgressBar(1000, fmt=ProgressBar.FULL) …
```
=> add  progressbar capability to Scipion

pyworkflow/em/constants.py, pyworkflow/em/protocol/protocol_sets.py, pyworkflow/gui/project/viewprojects.py, pyworkflow/object.py, pyworkflow/tests/em/protocols/test_protocols_sets.py
This PR has 3 small changes:
1.- The join sets was losing the ids as soon as there were conflicts. Now, if allowed, it will keep the id of the first set. This will allow the usage of other protocols that us the Id for matching items, at least for the first set that is being merged.
2.- Fixes a "bug"  in the _idCount of the sets
3.- Closes the bd after loading the project info in the project list window.
=> Join set do not loose ids of first set

pyworkflow/em/convert/atom_struct.py
PDBList __init__ has the default value  pdb=os.getcwd() unfortunately initializing parameters with something that is mutable is bad practice.  The reason for this is that the def statement only gets executed once, which is when the function is defined. Thus the initializer value only gets created once. For a reference type (as opposed to an immutable type which cannot change) like a function or a dictionary, this ends up as a visible and surprising pitfall, whereas for value types, it goes unnoticed.
In summary, we modify the call to PDBlist so it passes explicitly the value of the pdb argument.
Note, I do not modify PDBList.__init_definition  because is a biopython function, that is, belongs to an external module.
=> Fixed import from pdb

pyworkflow/em/convert/atom_struct.py, pyworkflow/em/data.py, pyworkflow/gui/form.py
* Introduced EXPOSE_ITEMS as static property in Set classes. It will be used in the GUI to allow (or not) to choose the subitems in the browser tree. Due to performance issues, it was (hardcoded) allowed only for SetOfVolumes and atomic structures. 
* Optional extra argument filterClassFunc to avoid some classes when operating with sets.
=> Minor changes introduced for Tomo
