pyworkflow/em/protocol/protocol_import/particles.py

FloatParam is imported inside params

FloatParam was not defined

---

pyworkflow/em/packages/igbmc/protocol_gempicker.py

* Added extra parameters for picking (GUI, Advanced level)
* References can be also a set of particles (e.g., reprojections), so pointerClass for references was modified
* Added help for the protocol
* Simple threshold check to stay in 0-1 range
* GPU-related options
* Other minor corrections of variable names and description
PS. I also propose to change module name to gempicker instead of igbmc (pyworkflow/em/packages/igbmc -> pyworkflow/em/packages/gempicker)

igbmc-gempicker improved protocol

---

pyworkflow/em/packages/grigoriefflab/viewer.py

Otherwise, the last "2sigma" graph is not shown

fix ctffind viewer

---

pyworkflow/em/packages/xmipp3/viewer_cl2d.py

Just testing the PR methodology on protected branches

used **kwargs standard

---

.travis.yml
pyworkflow/tests/em/programs/test_programs_xmipp.py

Fixed the gold standard folder for picking test

Fix testpicking

---

pyworkflow/em/packages/gctf/viewer.py

fix error in gctf plot, introduced in 17c0e8f

fix error in gctf plot, introduced in 17c0e8f

---

pyworkflow/em/packages/spider/scripts/mda/center1.msa
pyworkflow/em/packages/spider/scripts/mda/pairwise.msa
pyworkflow/tests/em/protocols/test_protocols_spider_align.py

fixed undefined [one] var in spider pairwise align protocol

---

pyworkflow/tests/em/programs/test_programs_xmipp.py

Ml2d tests are running, but with random seed and nothing else is really tested.

added random to ml2d tests

---

software/em/xmipp/java/src/xmipp/viewer/models/GalleryData.java
software/em/xmipp/java/src/xmipp/viewer/scipion/ScipionGalleryJFrame.java
software/em/xmipp/java/src/xmipp/viewer/windows/GalleryJFrame.java

Fixed:
- Removal of last element and changing view.
- Wrong change of mode after remove row or column
- Apply geo for particles assigned to a class

Showj fixs

---

install/script.py
pyworkflow/em/data.py
pyworkflow/em/packages/resmap/protocol_resmap.py
pyworkflow/em/packages/resmap/viewer_resmap.py
pyworkflow/tests/__init__.py
pyworkflow/tests/em/protocols/test_protocols_resmap.py

Fix some issues with ResMap resolution slices figure

---

software/em/xmipp/libraries/reconstruction/micrograph_automatic_picking2.cpp
software/em/xmipp/libraries/reconstruction/micrograph_automatic_picking2.h

Now we compute the Fourier transform of polar channels once.

Computing the fourier transform of polar images has been changed

---

scipion
scripts/tar.py

print the nickname and exclude *.tgz

---

pyworkflow/em/convert.py
pyworkflow/em/packages/eman2/eman2.py
pyworkflow/em/packages/eman2/protocol_autopick.py
pyworkflow/em/packages/eman2/protocol_boxing.py
pyworkflow/em/packages/eman2/protocol_initialmodel.py
pyworkflow/em/packages/eman2/protocol_reconstruct.py
pyworkflow/em/packages/eman2/protocol_refineasy.py
pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py
pyworkflow/em/packages/relion/convert.py
pyworkflow/em/packages/relion/protocol_autopick.py
pyworkflow/em/packages/relion/protocol_base.py
pyworkflow/em/packages/relion/protocol_classify3d.py
pyworkflow/em/packages/relion/protocol_polish.py
pyworkflow/em/packages/relion/protocol_preprocess.py
pyworkflow/em/packages/relion/protocol_reconstruct.py
pyworkflow/em/packages/relion/protocol_refine3d.py
pyworkflow/em/packages/xmipp3/protocol_projmatch/protocol_projmatch.py
pyworkflow/em/protocol/protocol.py
pyworkflow/gui/project/project.py
pyworkflow/gui/text.py
pyworkflow/protocol/protocol.py
scripts/tar.py

* Improved version validation in the config and made explicit how to edit the config.
* Centralized some validation about the dimensions of input particles and reference volume. Handle case of None input.
* Fixed bugs in the tar.py script when generating the source and binary tar files.

Several last-minute bug fixes

---

pyworkflow/em/packages/xmipp3/viewer.py
pyworkflow/em/protocol/protocol_sets.py
pyworkflow/tests/em/workflows/test_workflow_xmipp.py

fix rotational spectra view and protocol-subset condition

---

pyworkflow/em/data.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_crop_resize.py
pyworkflow/tests/em/protocols/test_protocols_xmipp_2d.py

Fixed important bug when resizing

---

pyworkflow/em/data.py
pyworkflow/em/packages/relion/protocol_preprocess.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_crop_resize.py
pyworkflow/em/protocol/protocol_alignment_assign.py
pyworkflow/tests/em/data/test_data.py
pyworkflow/tests/em/protocols/test_protocols_xmipp_2d.py

Fixed important scale bug after resizing.

RELEASE V1.0.0  2016-02-01 Second Try

---

pyworkflow/em/data.py
pyworkflow/tests/em/data/test_data.py

Two test have been created. 
./scipion test tests.em.data.test_data.TestFSC
Wait until fsc protocol have been modified before processing this request

added fsc object

---

pyworkflow/em/packages/grigoriefflab/convert.py
pyworkflow/em/packages/grigoriefflab/protocol_ctffind.py

This fixes ctffind protocol, that was missing few parameters when phase shift search was selected. Closes #320

Fix ctffind protocol

---

config/workflows/workflow_betagal1.json

tutorial workflow minor fix

---

pyworkflow/em/packages/relion/viewer.py

Raise exception if iter. selection is not provided. Please double check my corrections to the code.

Fix relion viewer

---

config/workflows/workflow_tutorial_intro.json
pyworkflow/em/packages/xmipp3/protocol_projmatch/viewer_projmatch.py

small fixes for Sciopion tutorial protocol

Fix import patterns for intro tutorial

---

pyworkflow/em/packages/eman2/protocol_autopick.py
pyworkflow/em/packages/emxlib/dataimport.py
pyworkflow/em/packages/relion/protocol_autopick.py
pyworkflow/em/packages/spider/protocol/protocol_classify_base.py
pyworkflow/em/packages/spider/scripts/mda/ca-pca.msa
pyworkflow/em/packages/spider/viewer.py
pyworkflow/em/packages/spider/viewer_capca.py
pyworkflow/em/packages/spider/viewer_classify.py
pyworkflow/em/packages/spider/viewer_refinement.py
pyworkflow/em/packages/xmipp3/protocol_ctf_micrographs.py
pyworkflow/em/packages/xmipp3/protocol_movie_alignment.py
pyworkflow/em/packages/xmipp3/viewer_cl2d.py
pyworkflow/em/protocol/protocol_ctf_assign.py
pyworkflow/em/protocol/protocol_import/coordinates.py
pyworkflow/em/protocol/protocol_import/ctfs.py

- commented out unused code for gnuplot
- updated help messages for Spider viewers and some protocols as well
- updated docstrings

added help for some Spider viewers

---

config/templates/scipion.template
pyworkflow/apps/pw_config.py
pyworkflow/gui/project/project.py
scipion

access: menu -> Project ->  notes
configuration: (in user scipion.conf)
[VARIABLES]
SCIPION_NOTES_PROGRAM = 
SCIPION_NOTES_ARGS = 
SCIPION_NOTES_FILE = notes.txt

added project notebook in menu

---

pyworkflow/em/data_tiltpairs.py
pyworkflow/em/packages/xmipp3/protocol_assignment_tilt_pair.py
pyworkflow/em/packages/xmipp3/protocol_particle_pick.py
pyworkflow/em/packages/xmipp3/protocol_particle_pick_pairs.py
pyworkflow/em/protocol/protocol.py
pyworkflow/em/protocol/protocol_particles.py
pyworkflow/gui/gui.py
pyworkflow/gui/project/viewprotocols.py
software/em/xmipp/libraries/reconstruction/image_assignment_tilt_pair.cpp

Summary and methods in tilt pairs protocols have been fixed

Fix output coordinates

---

pyworkflow/em/data_tiltpairs.py
pyworkflow/em/packages/eman2/e2converter.py
pyworkflow/em/packages/eman2/protocol_refineasy.py
pyworkflow/em/packages/xmipp3/protocol_assignment_tilt_pair.py
pyworkflow/em/packages/xmipp3/protocol_particle_pick_pairs.py
pyworkflow/em/protocol/protocol.py
pyworkflow/tests/em/workflows/test_workflow_xmipp_assignment_tiltpairs.py
pyworkflow/tests/em/workflows/test_workflow_xmipp_rct.py

Devel update 20160308

---

pyworkflow/protocol/protocol.py

fix split pattern in author list

---

.gitignore
pyworkflow/gui/project/viewprotocols.py
pyworkflow/monitor.py

viewprotocols.refreshRuns optimized (1/2 time reduced): not reloading the project when updating the tree.
This closes #381 
Connects to #379

Protocol refresh optimized (1/2 time reduced)

---

pyworkflow/em/packages/relion/protocol_base.py
pyworkflow/em/packages/relion/protocol_postprocess.py
pyworkflow/em/packages/relion/protocol_refine3d.py
pyworkflow/tests/em/protocols/test_protocols_relion.py

test of relion refine updated.
fixed summary for  relion postprocess.

relion bug related with generation of SetOfParticles from an intermediate iteration fixed.

---

pyworkflow/em/packages/xmipp3/protocol_validate_overfitting.py

now, the protocol take care if the input subsets are greater than 1/2 of set of input particles (instead of making Error message for the user)

modifying input subsets related code to avoid making error for useres

---

pyworkflow/em/packages/eman2/convert.py
pyworkflow/em/packages/eman2/protocol_refineasy.py
pyworkflow/em/packages/eman2/viewer.py
pyworkflow/em/packages/grigoriefflab/convert.py
pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py
pyworkflow/em/packages/grigoriefflab/protocol_refinement.py
pyworkflow/em/packages/grigoriefflab/viewer.py
pyworkflow/em/packages/relion/protocol_classify3d.py
pyworkflow/em/packages/xmipp3/protocol_projmatch/projmatch_form.py
pyworkflow/em/protocol/protocol_batch.py
software/em/xmipp/applications/tests/test_sampling/test_sampling_main.cpp
software/em/xmipp/libraries/data/sampling.cpp
software/em/xmipp/libraries/data/sampling.h
software/em/xmipp/libraries/parallel/mpi_angular_projection_matching.cpp
software/em/xmipp/resources/test/sampling/ref_i3h_sampling.xmd
software/em/xmipp/resources/test/sampling/ref_sampling.xmd

update devel branch with the last changes contained in v1.0

Devel update 20160427

---

pyworkflow/tests/em/workflows/test_workflow_mixed.py
software/em/xmipp/applications/tests/test_dimred/test_dimred_main.cpp

There is a modification for eman initial model test.
The second modification is to solve a discrepancy in a threshold value in dim red test. It was already fixed in DEVEL and this modification has been made to merge both.

V1.0 Parameters update

---

pyworkflow/gui/dialog.py
pyworkflow/gui/text.py

Clean the last new line/s when getting the text in a Text object.

Do not add final new lines in text values

---

software/em/xmipp/libraries/data/xvsmooth.cpp

fix abs() for unsigned int

---

software/em/xmipp/java/src/xmipp/viewer/scipion/ScipionGalleryJFrame.java

Hotfix show j freezes frequently

---

pyworkflow/em/protocol/protocol_import/dataimport.py

Update the 'devel' branch with the bugfixes from 'v1.0'.
@josuegbl , I created a branch to update devel with latest bug-fixes but I'm surprise of so few changes.  Have you done this in the recent days?

Devel update 20160614

---

software/em/xmipp/java/src/xmipp/viewer/models/MetadataTableModel.java

Closes #479 
Sorting 100.000 particles takes less than a second. Seems fine to me. Either for xmd and scipion sqlite.
I've added an hourglass to indicate sorting enabled.
I've added arrows for ascending or descending column order.

Show hourglass in the column header while sorting. Show sorting direction.

---

pyworkflow/gui/project/viewprotocols.py
pyworkflow/gui/tree.py
pyworkflow/project.py
pyworkflow/protocol/protocol.py
pyworkflow/utils/process.py

Invokes refresh runs the first time a project window is loaded and on manual refresh.
Closes #183

Check if PID is alive for running jobs when refreshing the desktop

---

pyworkflow/em/packages/atsas/protocol_pdb_to_saxs.py
pyworkflow/em/packages/xmipp3/protocol_multiple_fscs.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_filter.py
pyworkflow/em/packages/xmipp3/protocol_resolution3d.py

Jose Miguel, please, do not delete my branch after merging

Co small fixes

---

CHANGELOG.md
config/workflows/workflow_betagal1.json
config/workflows/workflow_tutorial_intro.json

Fixes in tutorial workflow templates,  committed by @azazellochg .
Updated the CHANGELOG.md

Fix tutorials workflow

---

install/script.py
pyworkflow/em/packages/eman2/convert.py
pyworkflow/em/packages/motioncorr/convert.py
scipion

Two minor fixes:
* Fixed typo in motioncor2 default value 
* Fixed eman2*rc script files. Fix #506 
Please DO NOT DELETE devel-fixes branch, we plan to use it for small fixes.

Devel fixes

---

pyworkflow/em/protocol/monitors/summary_provider.py
pyworkflow/em/wizard.py
pyworkflow/gui/browser.py
pyworkflow/gui/form.py
pyworkflow/gui/project/labels.py
pyworkflow/gui/project/viewprotocols.py
pyworkflow/gui/tree.py
pyworkflow/protocol/protocol.py

Treeview invokes sorting if provider allows it. 
FileTreeProvider implements sorting.
Closes #530

Sort objects in browse window

---

pyworkflow/em/data_tiltpairs.py
pyworkflow/em/packages/eman2/protocol_initialmodel.py
pyworkflow/em/packages/grigoriefflab/convert.py
pyworkflow/em/packages/grigoriefflab/protocol_unblur.py
pyworkflow/em/packages/spider/protocol/protocol_filters.py
pyworkflow/em/packages/spider/wizard.py
pyworkflow/em/packages/xmipp3/protocol_cl2d_align.py
pyworkflow/em/protocol/protocol_batch.py
pyworkflow/em/protocol/protocol_import/coordinates.py

@azazellochg  has fixed several issues:
- Bug when writing TiltPairs inner sets and another issue with subsets.
- Wrong parameters for Spider filter 
- Properly read shifts for Unblur protocol
- Validate number of MPI for cl2d_align

Several fixes

---

software/em/xmipp/external/delaunay/delaunay.cpp
software/em/xmipp/external/delaunay/delaunay.h
software/em/xmipp/libraries/reconstruction/image_assignment_tilt_pair.cpp
software/em/xmipp/libraries/reconstruction/image_assignment_tilt_pair.h

New functionality has been added to Delaunay to iterate through all faces of the triangulation. This optimizes the performance of the assignment tilt pair method.

Speed improvement in the method assignment tilt pair

---

pyworkflow/em/packages/xmipp3/protocol_multireference_alignability.py
pyworkflow/em/packages/xmipp3/viewer.py
software/em/xmipp/libraries/reconstruction/multireference_aligneability.cpp

1) Fixed one potential problem in the C++ method
2) Added a new advanced parameter in the protocol
3) Added a custor viewer

Jv multireference alignability

---

pyworkflow/em/protocol/protocol_batch.py
scripts/scipionbox_wizard.py

@azazellochg removed label from base protocols
Minor correction in the session wizard for scipion-box

Minor fixes

---

pyworkflow/gui/project/notifier.py
pyworkflow/tests/em/protocols/test_notifier.py

notifies now checks if the workflow has changed before sending the data to the webservice (I hope this will save a few dyno-hours)

Notify updates

---

pyworkflow/em/packages/xmipp3/protocol_ml2d.py

fix output path of images.xmd when run in F mode

---

pyworkflow/em/protocol/protocol_extract_coordinates.py

Closes #646 
Need more testing for cases of 2d/3d alignment.

apply shifts when extr coords

---

pyworkflow/em/packages/xmipp3/__init__.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_add_noise.py
pyworkflow/em/packages/xmipp3/protocol_resolution_monogenic_signal.py
pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py

MonoRes protocol and viewer have been modified, in particular next changes were performed 
1) A colorbar in the chimera viewer were included.
2) The creation of the chimera script has been moved from the protocol to the viewer
3) The colormap can be chosen in the viewer and customized
4) Viewer menu has been reordered and looks better
5) the summary shows the resolutions range

Mono res fixes

---

scripts/mirror_directory.sh

Sync two folders using batch file. Useful to copy movies as they are produced in a new external disk

 create script to mirror two directories

---

pyworkflow/gui/project/viewprotocols.py

DO not fail if there is something wrong in protocols.conf ,

---

pyworkflow/__init__.py
pyworkflow/em/packages/grigoriefflab/protocol_summovie.py
pyworkflow/em/packages/grigoriefflab/protocol_unblur.py
pyworkflow/em/packages/motioncorr/protocol_motioncorr.py
pyworkflow/em/packages/xmipp3/protocol_movie_opticalflow.py
pyworkflow/em/protocol/protocol_align_movies.py
pyworkflow/em/protocol/protocol_import/coordinates.py
pyworkflow/gui/project/base.py
pyworkflow/gui/project/project.py
pyworkflow/gui/text.py
pyworkflow/protocol/protocol.py
pyworkflow/utils/utils.py

This is a minor change to fix a case where alignment validation throws an exception instead of registering an error. 
Can this be merged into devel?

Fix validation error

---

pyworkflow/em/data.py
pyworkflow/em/packages/xmipp3/pdb/protocol_convert_pdb.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_create_mask2d.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_create_mask3d.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_crop_resize.py
pyworkflow/em/packages/xmipp3/protocol_resolution_monogenic_signal.py
pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py
pyworkflow/em/protocol/monitors/summary_provider.py
pyworkflow/em/protocol/protocol_extract_coordinates.py
pyworkflow/em/protocol/protocol_import/images.py
pyworkflow/em/protocol/protocol_import/volumes.py
pyworkflow/em/protocol/protocol_tiltpairs.py
pyworkflow/tests/em/workflows/test_workflow_emx.py
pyworkflow/utils/properties.py
software/em/xmipp/applications/programs/movie_optical_alignment_cpu/movie_optical_alignment_cpu.cpp
software/em/xmipp/libraries/reconstruction/resolution_monogenic_signal.cpp

Scipion performance when a project contains MonoRes protocol has been enhanced
Noise estimation for two half volumes has been enhanced
Reference to the wiki with the manuscript is included

Monores halves

---

install/funcs.py
install/script.py

definition of FFTW vars to use SCIPION FFTW libs

Allow definition of environment variables at install time

---

pyworkflow/em/protocol/protocol_import/particles.py

fix issue #827 
Now test
> ./scipion test tests.em.workflows.test_workflow_emx.TestEmxWeb
works

emx import need absolute path for import emx files

---

config/templates/scipionbox.template
scripts/mirror_directory.sh
scripts/scipionbox_wizard.py

Modify backup script so it is more difficult to overwrite data. Of course some user will find a way around.

Rm scipionbox

---

config/templates/scipionbox.template
pyworkflow/em/packages/relion/viewer.py
pyworkflow/em/protocol/protocol_batch.py
pyworkflow/em/viewer_fsc.py
scripts/mirror_directory.sh
scripts/scipionbox_wizard.py

Now the createFSC button works as expected (the button appears in FSC plot create from "in-memory" FSC). I have modified relion-refine and relion-postprocess so they use it.  
NOTE: I see that I have branched from rm_scipionbox (I previous pull request)

Rm fsc button

---

install/script.py

fix eman install

---

pyworkflow/em/protocol/protocol_import/base.py
pyworkflow/em/protocol/protocol_import/images.py
pyworkflow/tests/em/protocols/test_protocols_import_micrographs.py

Shows error message when special characters in path.
Allows multiple wildcards in import pattern

fix special characters in import protocols

---

pyworkflow/em/packages/spider/protocol/protocol_align_apsr.py
pyworkflow/em/packages/spider/protocol/protocol_align_base.py
pyworkflow/em/packages/spider/protocol/protocol_ca_pca.py
pyworkflow/em/packages/spider/protocol/protocol_classify_base.py
pyworkflow/em/packages/spider/protocol/protocol_custommask.py
pyworkflow/em/packages/spider/protocol/protocol_filters.py
pyworkflow/em/packages/spider/protocol/protocol_projmatch.py
pyworkflow/em/packages/spider/protocol/protocol_reconstruct.py
pyworkflow/em/packages/spider/scripts/mda/apsr4class.msa
pyworkflow/em/packages/spider/scripts/mda/binarytree.msa
pyworkflow/em/packages/spider/scripts/mda/ca-pca.msa
pyworkflow/em/packages/spider/scripts/mda/cluster.msa
pyworkflow/em/packages/spider/scripts/mda/filtershrink.msa
pyworkflow/em/packages/spider/scripts/mda/hierarchical.msa
pyworkflow/em/packages/spider/scripts/mda/highpass.msa
pyworkflow/em/packages/spider/scripts/mda/kmeans.msa
pyworkflow/em/packages/spider/scripts/mda/pairwise.msa
pyworkflow/em/packages/spider/scripts/projmatch/Refinement/refine.pam
pyworkflow/em/packages/spider/scripts/projmatch/Refinement/refine_settings.pam
pyworkflow/em/packages/spider/scripts/recons_fourier.txt

1. threading now works in most protocols (refinement not tested since there is no test protocol)
2. change csh to sh for more compatibility
3. add output generation in spider reconstruct protocol
Closes #946

spider fixes

---

pyworkflow/em/packages/xmipp3/protocol_resolution_monogenic_signal.py
pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py
software/em/xmipp/libraries/reconstruction/resolution_monogenic_signal.cpp
software/em/xmipp/libraries/reconstruction/resolution_monogenic_signal.h

The performance of monores has been enhanced
A bug in the calculation of the monogenic amplitude has been solved

monores changes for pull request

---

pyworkflow/apps/pw_protocol_list.py
pyworkflow/em/packages/opic/protocol_localized.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_filter.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_image_operate.py
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_mask.py

Release 1.1 hide parallel section

---

config/templates/protocols.template
pyworkflow/config.py
pyworkflow/em/packages/relion/protocol_autopick.py
pyworkflow/em/packages/relion/protocol_autopick_v2.py
pyworkflow/protocol/protocol.py

Added  isDisabled class method for protocols.
Test isDisabled when loading protocols, searching, of when loading the protocols.conf. Disable relion picking protocols dynamically, based on installed version

Hide disabled protocols (to hide relion picking protocols)

---

pyworkflow/em/packages/spider/scripts/projmatch/Refinement/refine_settings.pam

fixed missing nummps params

---

README.md
pyworkflow/em/packages/xmipp3/viewer_resolution3d.py
pyworkflow/gui/project/project.py
pyworkflow/project.py
pyworkflow/viewer.py

Bringing release-1.1.1 hot fixes

Facilities fixes

---

pyworkflow/em/packages/xmipp3/viewer.py

Added XmippProtExtractParticles as target in Xmipp/viewer.py

---

pyworkflow/em/convert.py
pyworkflow/em/packages/xmipp3/protocol_extract_particles_movies.py
pyworkflow/tests/em/protocols/test_protocols_xmipp_movies.py

This PR sould fix an error that occurs when the partcles from movies wants to be extract

fix extract movie particles

---

scripts/create_project.py
scripts/schedule_project.py

create_project.py script to create a project from a scipion workflow file (json)
schedule_project.py to schedule all protocols given a project name (already existing project)

create and schedule project scripts

---

pyworkflow/em/protocol/protocol_import/micrographs.py

avoid failing when sending back socket info

---

pyworkflow/em/packages/relion/viewer.py

Fixed relion classes distribution plot for 3D classification case

---

pyworkflow/gui/project/project.py
pyworkflow/project.py
pyworkflow/utils/properties.py

Release 1.1.facilities readonlyproject

---

pyworkflow/em/packages/xmipp3/protocol_extract_particles_movies.py
pyworkflow/em/protocol/protocol_movies.py

This PR should fix #1154 and #1155

Release 1.1.1 extract movie particles

---

pyworkflow/em/packages/xmipp3/protocol_movie_correlation.py
pyworkflow/em/packages/xmipp3/protocol_movie_opticalflow.py
pyworkflow/em/protocol/protocol_align_movies.py
pyworkflow/em/protocol/protocol_import/base.py
pyworkflow/em/protocol/protocol_import/images.py

Release 1.1.facilities dash in filename #1073

---

pyworkflow/gui/project/notifier.py

Do not fail when reporting usage fails!

Catch any exception when notifying usage

---

pyworkflow/tests/em/protocols/test_protocols_motioncor2.py

fix MC2 test

---

software/em/xmipp/java/src/xmipp/utils/XmippWindowUtil.java
software/em/xmipp/java/src/xmipp/viewer/windows/PlotJDialog.java

fix plots of multiple series (eg CL2D)

---

pyworkflow/em/packages/xmipp3/protocol_extract_particles.py
pyworkflow/em/wizard.py

Fix volume name before showing the filter volume wizzard

---

config/templates/execution.summary.template.html
pyworkflow/em/protocol/monitors/protocol_monitor_ctf.py
pyworkflow/em/protocol/monitors/protocol_monitor_summary.py
pyworkflow/em/protocol/monitors/protocol_monitor_system.py
pyworkflow/em/protocol/monitors/report_html.py

closes #1300 - add option to pause automatic refresh
closes #1308 - minor tweaks and adding resolution data
closes #1268 - fixes wrong ctf plot mic indexes

Facilities - html report fixes

---

pyworkflow/em/protocol/protocol_import/images.py
pyworkflow/em/protocol/protocol_import/micrographs.py

This PR should fix several errors such as:
- import individual frames that have the same names among all movies
for instance : movie1/frame1.mrc, movie2/frame1.mrc 
- no import all files that are already imported.

Facilities fix import

---

pyworkflow/project.py
pyworkflow/protocol/protocol.py

Fix wrong input set size when working in streaming

---

.gitignore
install/script.py
pyworkflow/em/data.py
pyworkflow/em/packages/gctf/convert.py
pyworkflow/em/packages/grigoriefflab/convert.py
pyworkflow/em/packages/relion/convert.py
pyworkflow/em/packages/xmipp3/convert.py
pyworkflow/tests/__init__.py
pyworkflow/tests/em/data/test_convert_relion.py
pyworkflow/tests/em/protocols/test_protocols_ctf_streaming.py

Manage phaseShift:
Relion convert phaseShift from CTFModel and back
Test the conversion
Xmpp does not use phaseShift
Closes #1494 
Sorry to bother guys, but since we are close to the release...I would appreciate your review on this. 8 eyes are better than my poor 2.

Release 1.1.facilities fixes

---

pyworkflow/em/convert_header/CCP4/convert.py
pyworkflow/em/data.py
pyworkflow/em/packages/ccp4/protocol_coot.py
pyworkflow/em/packages/ccp4/protocol_refmac.py
pyworkflow/em/packages/ccp4/viewer_coot.py
pyworkflow/em/packages/ccp4/viewer_refmac.py
pyworkflow/em/packages/chimera/protocol_fit.py
pyworkflow/em/packages/chimera/protocol_operate.py
pyworkflow/em/packages/chimera/test_protocol_chimera_operate.py
pyworkflow/em/packages/chimera/viewer.py
pyworkflow/em/packages/powerfit/protocol_powerfit.py
pyworkflow/em/packages/xmipp3/pdb/protocol_pseudoatoms.py
pyworkflow/em/packages/xmipp3/pdb/protocol_pseudoatoms_base.py
pyworkflow/em/packages/xmipp3/protocol_extract_unit_cell.py
pyworkflow/em/packages/xmipp3/tests/test_protocol_extract_unit_cell.py
pyworkflow/em/packages/xmipp3/viewer_extract_unit_cell.py
pyworkflow/em/protocol/protocol_import/viewer.py
pyworkflow/em/protocol/protocol_import/volumes.py
pyworkflow/em/viewer.py
pyworkflow/em/viewers/chimera_utils.py
pyworkflow/em/wizard.py
pyworkflow/gui/form.py
pyworkflow/tests/em/protocols/test_protocols_import_volumes.py
pyworkflow/tests/em/workflows/test_workflow_modeling.py
software/em/xmipp/libraries/data/unitCell.cpp

Revert "Model 05 refmac"

---

SConstruct

Ported fix by akesandgren

---

pyworkflow/em/packages/motioncorr/protocol_motioncorr.py

Updated help for advanced options in Motioncor2 1.1.0

---

install/script.py
pyworkflow/em/convert_atom_struct.py
pyworkflow/tests/em/data/test_convert_atom_struct.py

This code is able to read/write atomic structure files from/to disk and convert among PDB/MMCIF (The aim is similar to imageHandler but for atomic structure files)
dependencies: biopython module
Tests: ./scipion test tests.em.data.test_convert_atom_struct.TestAtomicStructHandler

handler for PDB/MMCIF files

---

pyworkflow/em/packages/xmipp3/bibtex.py
pyworkflow/em/packages/xmipp3/protocol_resolution_monogenic_signal.py
pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py
pyworkflow/tests/em/protocols/test_protocols_monores.py
software/em/xmipp/libraries/reconstruction/resolution_monogenic_signal.cpp
software/em/xmipp/libraries/reconstruction/resolution_monogenic_signal.h

Next changes were carried out:
-mask can be calculated automatically
-resolution range can be calculated automatically
-use of threads in the Fourier transform
-code performance
-cleaning code
-

monores: Fully automatic

---

pyworkflow/gui/form.py
pyworkflow/project.py
pyworkflow/protocol/protocol.py
pyworkflow/utils/properties.py

The 2d-streamer protocol already introduced the possibility to schedule runs after completion of some previous runs. 
This PR allows the users to select these preRequisites in a simple maner: The list of protocol IDs can be provided and the run will be scheduled...and not started until all preRequisites are finished.
Minor code clean-up was done in form.py

Release 1.2.1 schedule select

---

pyworkflow/tests/tests.py
scripts/sync_data.py

Allow tests dataset from other locations:

---

config/templates/execution.summary.template.html

limit x axis of resolution chart to 20
use https for highcharts.js.

Html report minor fixes

---

pyworkflow/em/protocol/protocol_particles.py

Close extract particles outputset

---

pyworkflow/em/packages/xmipp3/viewer.py
pyworkflow/em/viewer.py

Show Gain when pressing "Analyze results" button #1676.

---

pyworkflow/gui/project/base.py

- Fixing labels stop after a while

 -Fixing labels stop after a while

---

pyworkflow/manager.py

On behalf of @fonsecareyna82.
Closes #1700

Fix error when deleting a project in manager.py

---

pyworkflow/em/protocol/protocol_movies.py
pyworkflow/gui/browser.py
pyworkflow/tests/__init__.py
pyworkflow/tests/em/protocols/test_protocols_motioncor2.py

Convert gain and dark images if needed in a first step. For all movie alignment protocols. Test all combinations and step creation and dependency.

Convert gain

---

install/script.py

Blank space missing in string concatenation for openCVflags

Bug fixing in string concatenation

---

.travis.yml
sonar-project.properties

Travis + SonarCloud (Python only)

Enabling CI

---

pyworkflow/em/convert.py
pyworkflow/em/packages/xmipp3/protocol_particle_pick_pairs.py
pyworkflow/em/showj.py
pyworkflow/gui/gui.py
pyworkflow/project.py
pyworkflow/protocol/protocol.py

Closes #1767 
And tilt pair - showJ issue with memory (hope is the last one!)

Release 1.2.1 fixes

---

pyworkflow/em/packages/relion/dataimport.py

I have checked import with/without data extension. Works for me. Import tests are also ok.

close #1772

---

pyworkflow/gui/browser.py
pyworkflow/gui/project/viewprotocols.py

Fix Bug/feature request for export workflow GUI window

* Fix Bug/feature request for export workflow GUI window

---

config/templates/protocols.template
pyworkflow/gui/project/viewprojects.py

Rescue catching errors when a folder is not a scipion project.

Fix protocols.template format

---

install/install-plugin.py
install/plugin_funcs.py

Get plugin information from PIP when the version do not specified

Get plugin information from PIP when the version do not specified

---

pyworkflow/em/packages/xmipp3/viewer.py

Analize results for movies was failing when gainFile was empty

Added check to see if gainFile is None before using it

---

pyworkflow/gui/form.py

* not editable params are flat now, and keep the grey color
* widgets are better aligned, labels entries and buttons.
* sticky params attribute changed to be more responsive to size, especially width.
* Line param bug is fixed (no showing help buttons).
* some widgets have names to improve debugging.
Closes #1732 
Default load:
Responsive to width:
Fixed bugs:
NOTE: when activating the expert mode...scrolls are both active and the horizontal shouldn't. This was better before, but a small resize of its width fixed this and all widgets are shown without the need to maximize the window. Which some cases, with a large amount of expert params, was impossible to show them.

Form fixes and tweaks

---

install/install-plugin.py

Add flag --devel to make it possible to install local plugins without having a plugins.json, e.g.
`scipion installp -p path/to/pluginName --devel`

add devel mode to install plugins

---

scripts/scipionbox_report_statistics.py

I guess this is useful, right?
I found this in a stale branch. @rmarabini ?

Rm report scipionbox statistics

---

pyworkflow/em/packages/cryomethods/protocol_base.py
pyworkflow/em/packages/relion/protocol_base.py
pyworkflow/em/packages/relion/protocol_initialmodel.py

Fix a minor typo.

---

config/templates/protocols.template
pyworkflow/em/viewers/__init__.py
pyworkflow/em/viewers/chimera_server.py
pyworkflow/em/viewers/showj.py
pyworkflow/em/viewers/viewer_chimera.py
pyworkflow/gui/plugin_manager.py
pyworkflow/gui/project/project.py
pyworkflow/project.py
pyworkflow/tests/em/workflows/test_workflow_modeling.py
pyworkflow/tests/em/workflows/test_workflow_streaming.py
pyworkflow/webservices/notifier.py
scripts/stop_project.py

Threads named
Protocols added to protcols.conf: PowerfitProtRigidFit, ChimeraModelFromTemplate
StopProject script stops only active runs and catches errors.

Devel pluginization fixes

---

pyworkflow/em/protocol/protocol_micrographs.py
pyworkflow/em/protocol/protocol_movies.py

This fixes the mistake made by copy-pasting.

fix updateStreamState func

---

pyworkflow/em/viewers/viewers_data.py

Last changes from devel (and master)...after this....pluginization should be able to go back to devel.

Devel to pluginization

---

pyworkflow/project/config.py
pyworkflow/project/project.py
pyworkflow/templates/protocols.template

Creating the protocol_tree_view from the plugins procols.conf file

dynamic_protocols_tree

---

pyworkflow/gui/browser.py
pyworkflow/gui/project/viewprotocols.py
pyworkflow/protocol/protocol.py

Closes #1824 when steps are not in order (children is found before it's parent - streaming case)

Fix steps tree

---

pyworkflow/em/protocol/protocol_tests.py
pyworkflow/gui/form.py
pyworkflow/object.py
pyworkflow/protocol/params.py
pyworkflow/protocol/protocol.py
pyworkflow/tests/test_protocol_output.py

Also, validation errors at runtime do not print the trace.

Allowing choosing pointers to Scalars in the GUI

---

pyworkflow/install/funcs.py
pyworkflow/plugin.py

Fixing inconsistency in emFolder

---

pyworkflow/em/__init__.py
pyworkflow/em/wizard.py
pyworkflow/em/wizards.py
pyworkflow/gui/dialog.py

Discover em wizards

---

pyworkflow/__init__.py
pyworkflow/gui/plugin_manager.py
pyworkflow/gui/project/project.py
pyworkflow/project/config.py
pyworkflow/project/project.py
scipion

Fixing the way to launch Scipion from diferent config files path (--config some_path/scipion.conf)

Scipion config fix

---

pyworkflow/em/data.py

getDimensions has no return statement

fix getDimensions

---

pyworkflow/em/protocol/protocol_align_movies.py

partly addressing https://github.com/I2PC/xmipp/issues/132

Ds psd optimizations

---

pyworkflow/em/viewers/plotter.py
pyworkflow/gui/plotter.py

scatterPlot functionality added

---

pyworkflow/tests/em/workflows/test_workflow_streaming.py

This test now check:
* All movies are imported.
* Last processing protocol (CTF or whatever) have processed all data.
* Summary Monitor is finished after a while.
* All protocols are finished at the end (to check that finish cascade is working).
I want to include more protocols to this test in order to check as more real acquisition as possible.

Updating StreamingWorkflowTest

---

pyworkflow/templates/protocols.template

add rct section

---

pyworkflow/em/wizard.py

to avoid division by 0, change to 0.01 (freq) or 1 (A or px)

fix min values in wizards

---

pyworkflow/em/constants.py

Added constant to describe Dy symmetries (used by Cryosparc)

Distinguish between Dx and Dy symmetries

---

pyworkflow/gui/plotter.py

Change the style of the plots if this keyword is provided. The default is what we currently have, so the current Scipion should not see any difference.

Use style if provided

---

.travis.yml
pyworkflow/em/protocol/protocol_align_movies.py
pyworkflow/em/protocol/protocol_particles_picking.py
pyworkflow/em/protocol/protocol_sets.py
pyworkflow/gui/form.py
pyworkflow/gui/plugin_manager.py
pyworkflow/gui/text.py
pyworkflow/mapper/sqlite.py
pyworkflow/object.py

I'm creating this premature PR to annotate the issues I'm closing. No need to accept it  yet.
Closes #1992

small fixes

---

pyworkflow/apps/pw_schedule_run.py
pyworkflow/em/protocol/protocol_tests.py
pyworkflow/protocol/protocol.py
pyworkflow/tests/test_protocol_export.py
pyworkflow/tests/test_protocol_output.py

json export test
Validate PointerList

Json multipointer to sets

---

pyworkflow/em/protocol/protocol_align_movies.py
pyworkflow/em/protocol/protocol_micrographs.py

Fix #2030, #1854 and https://github.com/scipion-em/scipion-em-gctf/issues/10

Return FAILED_all.txt to movie alignment and ctf protocols
